name: Pull Requests owner approve action

on: pull_request

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == github.repository_owner
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
